/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Click Intern Core API
 * Internal platform API for internship tracking, assessments, and administration
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from './api-instance';
export interface LoginDto {
  email: string;
  /** @minLength 6 */
  password: string;
}

export type PublicUserDtoRole = (typeof PublicUserDtoRole)[keyof typeof PublicUserDtoRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PublicUserDtoRole = {
  ADMIN: 'ADMIN',
  MENTOR: 'MENTOR',
  INTERN: 'INTERN',
} as const;

export interface PublicUserDto {
  id: string;
  email: string;
  fullName: string;
  role: PublicUserDtoRole;
  createdAt: string;
}

export interface AuthTokensResponseDto {
  accessToken: string;
  refreshToken: string;
  user: PublicUserDto;
}

export type ApiErrorResponseDtoMessage = string | string[];

export interface ApiErrorResponseDto {
  statusCode: number;
  error: string;
  message: ApiErrorResponseDtoMessage;
}

export interface RefreshTokenDto {
  refreshToken: string;
}

export interface LogoutResponseDto {
  success: boolean;
}

export interface MentorBriefDto {
  id: string;
  fullName: string;
  email?: string;
}

/**
 * @nullable
 */
export type InternProfileMetaDtoMentor = MentorBriefDto | null;

export interface InternProfileMetaDto {
  id: string;
  mentorId: string;
  /** @nullable */
  mentor?: InternProfileMetaDtoMentor;
}

export type AdminUserDtoRole = (typeof AdminUserDtoRole)[keyof typeof AdminUserDtoRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminUserDtoRole = {
  ADMIN: 'ADMIN',
  MENTOR: 'MENTOR',
  INTERN: 'INTERN',
} as const;

/**
 * @nullable
 */
export type AdminUserDtoInternProfile = InternProfileMetaDto | null;

export interface AdminUserDto {
  id: string;
  email: string;
  fullName: string;
  role: AdminUserDtoRole;
  createdAt: string;
  /** @nullable */
  internProfile?: AdminUserDtoInternProfile;
}

export type CreateUserDtoRole = (typeof CreateUserDtoRole)[keyof typeof CreateUserDtoRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUserDtoRole = {
  ADMIN: 'ADMIN',
  MENTOR: 'MENTOR',
  INTERN: 'INTERN',
} as const;

export interface CreateUserDto {
  email: string;
  fullName: string;
  role: CreateUserDtoRole;
  /** @minLength 6 */
  password: string;
  mentorId?: string;
}

export type UpdateUserDtoRole = (typeof UpdateUserDtoRole)[keyof typeof UpdateUserDtoRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserDtoRole = {
  ADMIN: 'ADMIN',
  MENTOR: 'MENTOR',
  INTERN: 'INTERN',
} as const;

export interface UpdateUserDto {
  fullName?: string;
  role?: UpdateUserDtoRole;
  mentorId?: string;
}

export interface CriterionResponseDto {
  id: string;
  title: string;
  description: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  maxScore: number;
}

export interface AssessmentMentorDto {
  id: string;
  fullName: string;
}

export interface AssessmentResponseDto {
  id: string;
  internId: string;
  mentorId: string;
  criterionId: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  score: number;
  /** @nullable */
  comment?: string | null;
  createdAt: string;
  criterion?: CriterionResponseDto;
  mentor?: AssessmentMentorDto;
}

/**
 * @nullable
 */
export type MentorInternProfileWithAssessmentsDtoMentor = MentorBriefDto | null;

export interface MentorInternProfileWithAssessmentsDto {
  id: string;
  /** @nullable */
  mentorId: string | null;
  /** @nullable */
  mentor?: MentorInternProfileWithAssessmentsDtoMentor;
  assessments: AssessmentResponseDto[];
}

/**
 * @nullable
 */
export type MentorAllInternListItemDtoInternProfile = MentorInternProfileWithAssessmentsDto | null;

export interface MentorAllInternListItemDto {
  id: string;
  fullName: string;
  email: string;
  /** @nullable */
  photoUrl?: string | null;
  /** @nullable */
  internProfile: MentorAllInternListItemDtoInternProfile;
}

export interface UserBriefDto {
  id: string;
  fullName: string;
  email: string;
  /** @nullable */
  photoUrl?: string | null;
}

export interface MentorInternListItemDto {
  id: string;
  userId: string;
  mentorId: string;
  user: UserBriefDto;
  assessments: AssessmentResponseDto[];
}

export interface MentorInternDto {
  id: string;
  userId: string;
  mentorId: string;
  user: UserBriefDto;
}

export interface MentorInternDetailDto {
  intern: MentorInternDto;
  criteria: CriterionResponseDto[];
  assessments: AssessmentResponseDto[];
}

export interface CreateAssessmentDto {
  internId: string;
  criterionId: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  score: number;
  comment?: string;
}

export interface CreateCriterionDto {
  title: string;
  description: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  maxScore: number;
}

export interface LeaderboardEntryDto {
  internId: string;
  userId: string;
  fullName: string;
  averageScore: number;
  totalAssessments: number;
}

export type UserSettingsDtoRole = (typeof UserSettingsDtoRole)[keyof typeof UserSettingsDtoRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserSettingsDtoRole = {
  ADMIN: 'ADMIN',
  MENTOR: 'MENTOR',
  INTERN: 'INTERN',
} as const;

/**
 * @nullable
 */
export type UserSettingsDtoPhone = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type UserSettingsDtoPhotoUrl = { [key: string]: unknown } | null;

export interface UserSettingsDto {
  id: string;
  email: string;
  fullName: string;
  role: UserSettingsDtoRole;
  createdAt: string;
  /** @nullable */
  phone?: UserSettingsDtoPhone;
  /** @nullable */
  photoUrl?: UserSettingsDtoPhotoUrl;
}

/**
 * Phone in E.164 format. Send empty string or "null" to clear value.
 * @nullable
 */
export type UpdateSettingsMultipartDtoPhone = { [key: string]: unknown } | null;

export interface UpdateSettingsMultipartDto {
  /**
   * Phone in E.164 format. Send empty string or "null" to clear value.
   * @nullable
   */
  phone?: UpdateSettingsMultipartDtoPhone;
  /** Set true to remove current photo. Cannot be combined with photo file in same request. */
  removePhoto?: boolean;
  /** Profile photo. Supported formats: JPEG, PNG, WebP. Max size: 5MB. */
  photo?: Blob;
}

export const authControllerLogin = (loginDto: LoginDto) => {
  return customInstance<AuthTokensResponseDto>({
    url: `/auth/login`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: loginDto,
  });
};

export const authControllerRefresh = (refreshTokenDto: RefreshTokenDto) => {
  return customInstance<AuthTokensResponseDto>({
    url: `/auth/refresh`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: refreshTokenDto,
  });
};

export const authControllerLogout = () => {
  return customInstance<LogoutResponseDto>({ url: `/auth/logout`, method: 'POST' });
};

export const usersControllerMe = () => {
  return customInstance<PublicUserDto>({ url: `/users/me`, method: 'GET' });
};

export const adminControllerListUsers = () => {
  return customInstance<AdminUserDto[]>({ url: `/admin/users`, method: 'GET' });
};

export const adminControllerCreateUser = (createUserDto: CreateUserDto) => {
  return customInstance<PublicUserDto>({
    url: `/admin/users`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createUserDto,
  });
};

export const adminControllerListMentors = () => {
  return customInstance<MentorBriefDto[]>({ url: `/admin/mentors`, method: 'GET' });
};

export const adminControllerUpdateUser = (id: string, updateUserDto: UpdateUserDto) => {
  return customInstance<PublicUserDto>({
    url: `/admin/users/${id}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateUserDto,
  });
};

export const adminControllerDeleteUser = (id: string) => {
  return customInstance<PublicUserDto>({ url: `/admin/users/${id}`, method: 'DELETE' });
};

export const assessmentsControllerListAllInterns = () => {
  return customInstance<MentorAllInternListItemDto[]>({ url: `/assessments/mentor/interns/all`, method: 'GET' });
};

export const assessmentsControllerListMentorInterns = () => {
  return customInstance<MentorInternListItemDto[]>({ url: `/assessments/mentor/interns`, method: 'GET' });
};

export const assessmentsControllerMentorInternDetail = (internId: string) => {
  return customInstance<MentorInternDetailDto>({ url: `/assessments/mentor/interns/${internId}`, method: 'GET' });
};

export const assessmentsControllerCreate = (createAssessmentDto: CreateAssessmentDto) => {
  return customInstance<AssessmentResponseDto>({
    url: `/assessments`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createAssessmentDto,
  });
};

export const assessmentsControllerAssignIntern = (internId: string) => {
  return customInstance<MentorAllInternListItemDto>({
    url: `/assessments/mentor/interns/${internId}/assign`,
    method: 'POST',
  });
};

export const criteriaControllerList = () => {
  return customInstance<CriterionResponseDto[]>({ url: `/criteria`, method: 'GET' });
};

export const criteriaControllerCreate = (createCriterionDto: CreateCriterionDto) => {
  return customInstance<CriterionResponseDto>({
    url: `/criteria`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createCriterionDto,
  });
};

export const internControllerMyAssessments = () => {
  return customInstance<AssessmentResponseDto[]>({ url: `/intern/me/assessments`, method: 'GET' });
};

export const internControllerLeaderboard = () => {
  return customInstance<LeaderboardEntryDto[]>({ url: `/intern/leaderboard`, method: 'GET' });
};

export const settingsControllerMe = () => {
  return customInstance<UserSettingsDto>({ url: `/settings/me`, method: 'GET' });
};

export const settingsControllerUpdateMe = (updateSettingsMultipartDto: UpdateSettingsMultipartDto) => {
  const formData = new FormData();
  if (updateSettingsMultipartDto.phone !== undefined && updateSettingsMultipartDto.phone !== null) {
    formData.append(`phone`, JSON.stringify(updateSettingsMultipartDto.phone));
  }
  if (updateSettingsMultipartDto.removePhoto !== undefined) {
    formData.append(`removePhoto`, updateSettingsMultipartDto.removePhoto.toString());
  }
  if (updateSettingsMultipartDto.photo !== undefined) {
    formData.append(`photo`, updateSettingsMultipartDto.photo);
  }

  return customInstance<UserSettingsDto>({
    url: `/settings/me`,
    method: 'PATCH',
    headers: { 'Content-Type': 'multipart/form-data' },
    data: formData,
  });
};

export type AuthControllerLoginResult = NonNullable<Awaited<ReturnType<typeof authControllerLogin>>>;
export type AuthControllerRefreshResult = NonNullable<Awaited<ReturnType<typeof authControllerRefresh>>>;
export type AuthControllerLogoutResult = NonNullable<Awaited<ReturnType<typeof authControllerLogout>>>;
export type UsersControllerMeResult = NonNullable<Awaited<ReturnType<typeof usersControllerMe>>>;
export type AdminControllerListUsersResult = NonNullable<Awaited<ReturnType<typeof adminControllerListUsers>>>;
export type AdminControllerCreateUserResult = NonNullable<Awaited<ReturnType<typeof adminControllerCreateUser>>>;
export type AdminControllerListMentorsResult = NonNullable<Awaited<ReturnType<typeof adminControllerListMentors>>>;
export type AdminControllerUpdateUserResult = NonNullable<Awaited<ReturnType<typeof adminControllerUpdateUser>>>;
export type AdminControllerDeleteUserResult = NonNullable<Awaited<ReturnType<typeof adminControllerDeleteUser>>>;
export type AssessmentsControllerListAllInternsResult = NonNullable<
  Awaited<ReturnType<typeof assessmentsControllerListAllInterns>>
>;
export type AssessmentsControllerListMentorInternsResult = NonNullable<
  Awaited<ReturnType<typeof assessmentsControllerListMentorInterns>>
>;
export type AssessmentsControllerMentorInternDetailResult = NonNullable<
  Awaited<ReturnType<typeof assessmentsControllerMentorInternDetail>>
>;
export type AssessmentsControllerCreateResult = NonNullable<Awaited<ReturnType<typeof assessmentsControllerCreate>>>;
export type AssessmentsControllerAssignInternResult = NonNullable<
  Awaited<ReturnType<typeof assessmentsControllerAssignIntern>>
>;
export type CriteriaControllerListResult = NonNullable<Awaited<ReturnType<typeof criteriaControllerList>>>;
export type CriteriaControllerCreateResult = NonNullable<Awaited<ReturnType<typeof criteriaControllerCreate>>>;
export type InternControllerMyAssessmentsResult = NonNullable<
  Awaited<ReturnType<typeof internControllerMyAssessments>>
>;
export type InternControllerLeaderboardResult = NonNullable<Awaited<ReturnType<typeof internControllerLeaderboard>>>;
export type SettingsControllerMeResult = NonNullable<Awaited<ReturnType<typeof settingsControllerMe>>>;
export type SettingsControllerUpdateMeResult = NonNullable<Awaited<ReturnType<typeof settingsControllerUpdateMe>>>;
